version: '2'
services:

  ###
  # Base app container. Inherited by dev and eventually prod containers.
  ###
  app:
    build:
      context: .
      dockerfile:  ./dockerfiles/app
    command: /data/code/scripts/rake-app.sh
    env_file:
      - ./dockerfiles/app.env
    working_dir: /data/code

  ###
  # Dev container extends the base application.
  ###
  dev:
    command: /data/code/scripts/rake-dev.sh
    extends:
      service: app
    links:
      - redis
      - postgres
    ports:
      - "4567:4567"
    volumes:
      - .:/data/code

  ###
  # Redis used for redis things we do.
  ###
  redis:
    image: redis

  ###
  # Postgres used for redis things we do.
  ###
  postgres:
    image: postgres
    env_file:
      - ./dockerfiles/app.env
