version: '2'
services:

  ###
  # Base app container. Inherited by dev and eventually prod containers.
  ###
  app:
    build:
      context: .
      dockerfile:  ./dockerfiles/app
    command: rake
    working_dir: /data/code
    env_file:
      - ./dockerfiles/app.env

  ###
  # Dev container extends the base application.
  ###
  dev:
    extends:
      service: app
    ports:
      - "4567:4567"
    volumes:
      - .:/data/code
    links:
      - redis
    command: rake test

  ###
  # Redis used for redis things we do.
  ###
  redis:
    image: redis
