version: '2'
services:

  ###
  # Base app container. Inherited by dev and eventually prod containers.
  ###
  app:
    build:
      context: .
      dockerfile:  ./dockerfiles/app
    env_file:
      - ./dockerfiles/app.env
    working_dir: /data/code
    volumes:
      - .:/data/code

  ###
  # Dev container extends the base application.
  ###
  dev:
    command: bash -c "sleep 20 && unicorn -l 4567 -c dockerfiles/unicorn.rb -E deployment"
    extends:
      service: app
    links:
      - testing-psql
      - testing-mysql
    depends_on:
      - test
      - migrate
    ports:
      - "4567:4567"

  ###
  # migrate container extends the base application.
  ###
  migrate:
    command: bash -c "sleep 10 && rake migrate"
    extends:
      service: app

  ###
  # test container extends the base application.
  ###
  test:
    command: rake spec
    extends:
      service: app
    links:
      - testing-psql
      - testing-mysql
    depends_on:
      - testing-psql
      - testing-mysql

  ###
  # Postgres database for testing.
  ###
  testing-psql:
    image: postgres
    env_file:
      - ./dockerfiles/app.env

  ###
  # MYSQL database for testing.
  ###
  testing-mysql:
    image: mysql
    env_file:
      - ./dockerfiles/app.env
