version: '2'
services:

  ###
  # Base app container. Inherited by dev and eventually prod containers.
  ###
  app:
    build:
      context: .
      dockerfile:  ./dockerfiles/app
    command: /data/code/scripts/rake-app.sh
    env_file:
      - ./dockerfiles/app.env
    working_dir: /data/code
    volumes:
      - .:/data/code

  ###
  # Dev container extends the base application.
  ###
  dev:
    command: /data/code/scripts/rake-dev.sh
    extends:
      service: app
    links:
      - postgres
    ports:
      - "4567:4567"

  ###
  # Postgres for databases.
  ###
  postgres:
    image: postgres
    env_file:
      - ./dockerfiles/app.env
